version: '3'
services:
  frontend-nginx-srv: 
    image: nginx:alpine
    container_name: frontend-nginx
    volumes:
      - ./frontend-nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend-nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  backend-app-srv:
    build: backend-app/.
    image: email-app:aug8
    container_name: backend-app
    expose:
      - "5000"
