apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: demo
  labels:
    app: web-app
    platform: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: python-web-app
        image: sreejithvu/email-app:v5
        ports:
        - containerPort: 5000
